const { getSessionById, updateSessionState, INTERVIEW_STATES } = require('../../models/session');
const { createTranscript } = require('../../models/transcript');
const crypto = require('crypto');

const SILENCE_THRESHOLD = 3;
const MAX_TURNS = 20;

function detectExitIntent(text) {
  if (!text) return false;
  const exitPhrases = ['thank you', 'i\'m done', 'that\'s all', 'no more', 'goodbye', 'bye', 'end interview', 'stop'];
  return exitPhrases.some(p => text.toLowerCase().includes(p));
}

exports.handler = async (event) => {
  try {
    const body = JSON.parse(event.body || '{}');
    const { sessionId, textTranscript, isSilence, currentConceptId } = body;

    if (!sessionId) {
      return { statusCode: 400, body: JSON.stringify({ error: 'sessionId required' }) };
    }

    const session = await getSessionById(sessionId);
    if (!session) {
      return { statusCode: 404, body: JSON.stringify({ error: 'Session not found' }) };
    }

    const turnIndex = session.turnCount || 0;

    // Handle silence
    if (isSilence) {
      const silenceCount = (session.silenceCount || 0) + 1;
      
      if (silenceCount >= SILENCE_THRESHOLD) {
        return {
          statusCode: 200,
          body: JSON.stringify({
            shouldTerminate: true,
            reason: 'SILENCE_TIMEOUT'
          })
        };
      }

      await updateSessionState(sessionId, session.state, { silenceCount });

      return {
        statusCode: 200,
        body: JSON.stringify({
          shouldTerminate: false,
          nextAIResponse: "I didn't catch that. Could you please repeat?",
          silenceCount
        })
      };
    }

    // Save user transcript
    await createTranscript({
      transcriptId: crypto.randomUUID(),
      sessionId,
      turnIndex,
      speaker: 'USER',
      text: textTranscript,
      timestamp: Date.now()
    });

    // Check exit intent
    if (detectExitIntent(textTranscript)) {
      return {
        statusCode: 200,
        body: JSON.stringify({
          shouldTerminate: true,
          reason: 'USER_EXIT'
        })
      };
    }

    // Check max turns
    if (turnIndex >= MAX_TURNS) {
      return {
        statusCode: 200,
        body: JSON.stringify({
          shouldTerminate: true,
          reason: 'MAX_TURNS_REACHED'
        })
      };
    }

    // Update session state
    await updateSessionState(sessionId, INTERVIEW_STATES.PROCESSING_RESPONSE, {
      currentConceptId: currentConceptId || session.currentConceptId,
      silenceCount: 0
    });

    return {
      statusCode: 200,
      body: JSON.stringify({
        shouldTerminate: false,
        nextAIResponse: null // Will be generated by generateAtomicTurn
      })
    };

  } catch (error) {
    console.error('Process User Input Error:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error.message })
    };
  }
};
